version: "3"

services:
  minio:
    image: "minio/minio"
    entrypoint: sh
    command: |
      -c '
      mkdir -p /var/run/minio/teamcity &&
      minio server /var/run/minio'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "accessKey"
      MINIO_SECRET_KEY: "secretKey"
    volumes:
      - "/var/run/minio"
  
  nightly_musl:
    build:
      context: scripts/nigthly_musl
    command: 
      - "/app/scripts/nigthly_musl/build.sh"
    volumes:
      - "./:/app"
    environment:
      AWS_ACCESS_KEY_ID: "accessKey"
      AWS_SECRET_ACCESS_KEY: "secretKey"
      S3_ENDPOINT: "http://minio:9000"
    working_dir: "/app"
