version: "3"

services:
  minio:
    image: "minio/minio"
    entrypoint: sh
    command: |
      -c '
      mkdir -p /var/run/minio/bucket &&
      minio server /var/run/minio'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "accessKey"
      MINIO_SECRET_KEY: "secretKey"
    volumes:
      - "/var/run/minio"
  
  rust_nightly_musl:
    image: "rustlang/rust:nightly"
    command: |
      bash -ex -c '
      apt-get update -qy                             &&
      apt-get install musl-tools -qq                 &&
      rustup target add x86_64-unknown-linux-musl    &&
      cargo fetch                                    &&
      cargo build $${CARGO_ARGS} --tests             &&
      cargo test $${CARGO_ARGS} -- --nocapture       &&
      cargo build $${CARGO_ARGS} --bin main --release'
    volumes:
      - "./:/app"
    environment:
      CARGO_ARGS: "--color always --target=x86_64-unknown-linux-musl"
      AWS_ACCESS_KEY_ID: "accessKey"
      AWS_SECRET_ACCESS_KEY: "secretKey"
      S3_ENDPOINT: "http://minio:9000"
    working_dir: "/app"
    depends_on:
      - minio