version: "3"

services:
  minio:
    image: "minio/minio"
    entrypoint: sh
    command: |
      -c '
      mkdir -p /var/run/minio/bucket &&
      minio server /var/run/minio'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "accessKey"
      MINIO_SECRET_KEY: "secretKey"
    volumes:
      - "/var/run/minio"
  
  nightly_musl:
    build:
      context: scripts/nigthly_musl
    command: |
      bash -ex -c '
      cargo fetch                                     &&
      cargo build $${CARGO_ARGS} --tests              &&
      cargo test $${CARGO_ARGS} -- --nocapture        &&
      cargo build $${CARGO_ARGS} --bin main --release &&
      upx target/$${TARGET}/release/main              &&
      true'
    volumes:
      - "./:/app"
    environment:
      TARGET: "x86_64-unknown-linux-musl"
      CARGO_ARGS: "--color always --target=x86_64-unknown-linux-musl"
      AWS_ACCESS_KEY_ID: "accessKey"
      AWS_SECRET_ACCESS_KEY: "secretKey"
    working_dir: "/app"
